import assert from "node:assert/strict";
import test from "node:test";
import { canTransitionDigitalRecord, publishedBooks, publishedLessons, validateLearningRecord, type LibraryCatalogRecord, type LearningCatalogRecord } from "./catalog.ts";
const book: LibraryCatalogRecord = { id:"b1", slug:"book", title:"Book", author:"Author", language:"ar", category:"Fiqh", pdfFileId:"file", pdfAssetId:"file", accessLevel:"public", published:true, status:"published" };
const lesson: LearningCatalogRecord = { id:"l1", courseId:"c1", courseTitle:"Fiqh 1", title:"Lesson 1", academicYear:"2026-2027", year:1, semester:1, order:1, attachmentFileIds:["a1"], attachmentAssetIds:["a1"], accessLevel:"student-only", published:true, status:"published" };
test("only valid published books reach public repository without Drive file ids",()=>{ const result = publishedBooks([book,{...book,id:"b2",status:"draft"}]); assert.equal(result.length,1); assert.equal("pdfAssetId" in result[0], false); assert.equal("coverAssetId" in result[0], false); });
test("learning year must match semester",()=>{ assert.ok(validateLearningRecord({...lesson,year:2}).some(e=>e.includes("match"))); });
test("only valid published lessons reach public repository without Drive file ids",()=>{ const result = publishedLessons([lesson,{...lesson,id:"l2",status:"archived"}],"c1"); assert.equal(result.length,1); assert.equal(result[0].courseTitle,"Fiqh 1"); assert.equal(result[0].semester,1); assert.equal("attachmentAssetIds" in result[0], false); assert.equal("videoAssetId" in result[0], false); });
test("digital lifecycle requires review before publish and reserves publish/archive for admin",()=>{ assert.equal(canTransitionDigitalRecord("editor","library","draft","published"),false); assert.equal(canTransitionDigitalRecord("editor","library","draft","review"),true); assert.equal(canTransitionDigitalRecord("academic-officer","learning","review","published"),false); assert.equal(canTransitionDigitalRecord("admin","learning","review","published"),true); });
